language: android
sudo: false
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
    - sys-img-armeabi-v7a-android-24
    - sys-img-x86-android-24
cache:
    directories:
        - node_modules
        - src/lib
install:
    - npm install -g ionic cordova
    - npm install
    - export PATH=$(npm bin):$PATH
    - bower install
script:
    - ionic platform add android
    - ionic resources
    - ionic build android
